package org.example.backend.entity;

public enum Status {
    NEW, SELECT_LANGUAGE, SELECT_ROLE, DRIVER_PAGE, PRICE_GO, DAY_MONTH, TIME_ENTER, NEW_NUMBER, SET_PASHOL, SET_FROM, SET_TO, SET_COUNT_SIDE, SET_GO_MONEY, SET_DAY_MONTH, SET_TIME, SET_PATH, START, COMPLETED, SET_DIRECTIONS, NEW_PRICE, NEW_DAY, SELECT_PATH
}
