package org.example.backend.entity;

public enum Status {
    NEW,SET_CITY_TO_SAVE, SELECT_LANGUAGE, SELECT_ROLE, DRIVER_PAGE, PRICE_GO, DAY_MONTH, TIME_ENTER, NEW_NUMBER, SET_PASHOL, SET_FROM, SET_TO, SET_COUNT_SIDE, SET_GO_MONEY, SET_DAY_MONTH, SET_TIME, SET_PATH, START, COMPLETED, SET_DIRECTIONS, NEW_PRICE, NEW_DAY, NEW_TIME, SET_CITY_TO, GET_PASSENGER_PATH, SET_CITY_FROM_SAVE, DIRECTIONS, BACK, COMMENT_CREATE, NONE, HOME_PAGE, HOME_PAGE_DRIVER, SET_FULL_NAME, SET_PHONE_NUMBER, SET_CAR, SET_MYSELF, SELECT_PATH
}
